<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PDFGenerator extends Controller
{
    public function __construct()
    {

    }

    public function generate_pdf( Request $request )
    {
        if ($request->getMethod('POST') ) {
            if ($request->has('html') ) {
                $today_date      = date("Y-m-d");
                $file_name       = "hspg_".uniqid() . '-' . $today_date . ".pdf";
                $file_path       = HS_TMP_FOLDER .$file_name;
                $html_to_convert = $request->input('html');
                $mpdf            = new \Mpdf\Mpdf(
                    [
                        'default_font' => 'montserrat'
                    ]
                );
                $mpdf->SetAuthor('HomeScript');
                $mpdf->SetCreator('Emmanuel from HomeScript');
                $mpdf->SetTitle('Document generated by HomeScript Generator.');
                $mpdf->WriteHTML($html_to_convert);
                $mpdf->Output($file_path, 'F');

                $url = url('/');
                if ($request::secure() ) {
                    $url = str_replace('http', 'https', $url);
                    var_dump($url, preg_replace('/http/','https', $url));
                }

                return response()->json(
                    array(
                        'code'     => '200',
                        'message'  => 'success',
                        'response' =>
                            array(
                                'input' => htmlspecialchars($html_to_convert),
                                'output' => $url.'/tmp_folder/'.$file_name,
                            )
                    )
                );
            }
        }

        return response()->json(
            array(
                'code'    => '403',
                'message' => 'error',
                 array(
                     'response' => "Aucun document spécifié nous ne pouvons".
                     "générer un pdf à partir des données fournies."
                 ),
            )
        );
    }
}
